services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: thy-case-study-backend:local
    env_file:
      - .env
    environment:
      PORT: "8082"
    ports:
      - "8082:8082"
    restart: unless-stopped
